### ISSUE TITLE
using nuclear probabilities or segmentations from StarDist

### ISSUE THREAD

**Issue by pr4deepr** [hci-unihd/plant-seg#109]
Hi
   Thank you for making this software available. 
I would like to use nuclear prediction label map from StarDist for the Lifted MultiCut segmentation as part of the Plantseg workflow. 
I had a look at previous closed Issues and it looks like it is possible. and have use following in the yml file

`is_segmentation: True`

and entered a `nuclei_predictions_path`
and 

However, I keep getting this error

`assert input_segmentation.shape == watershed.shape`

Complete log trace:

```
2022-02-09 19:03:06,194 [MainThread] INFO PlantSeg - Found 'predictions' dataset inside /home/rajasekhar.p/Documents/bianca_data/dapi_prob_map/membrane/PreProcessing/generic_light_sheet_3d_unet/membrane_predictions.h5
2022-02-09 19:03:09,537 [MainThread] INFO PlantSeg - Computing segmentation with dtWS...
2022-02-09 19:04:53,710 [MainThread] INFO PlantSeg - Clustering with LiftedMulticut...
Traceback (most recent call last):
  File "/home/rajasekhar.p/.conda/envs/plant-seg/bin/plantseg", line 10, in <module>
    sys.exit(main())
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/run_plantseg.py", line 28, in main
    raw2seg(config)
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/pipeline/raw2seg.py", line 85, in raw2seg
    output_paths = pipeline_step()
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/pipeline/steps.py", line 55, in __call__
    return [self.read_process_write(input_path) for input_path in self.input_paths]
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/pipeline/steps.py", line 55, in <listcomp>
    return [self.read_process_write(input_path) for input_path in self.input_paths]
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/segmentation/lmc.py", line 105, in read_process_write
    output_data = self.process(pmaps)
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/segmentation/lmc.py", line 73, in process
    segmentation = segment_volume_lmc_from_seg(boundary_pmaps,
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/segmentation/lmc.py", line 174, in segment_volume_lmc_from_seg
    lifted_uvs, lifted_costs = lifted_problem_from_segmentation(rag, watershed_segmentation, nuclei_seg,
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/elf/segmentation/features.py", line 529, in lifted_problem_from_segmentation
    assert input_segmentation.shape == watershed.shape

```

I am "Computing a rescaling factor" based on pixel size of the image and the membrane predictions generated during the liftedmulticut appear to be rescaled.  I've attached the yml file as txt.

[lifted_multicut.yml.txt](https://github.com/hci-unihd/plant-seg/files/8030685/lifted_multicut.yml.txt)

I'm assuming I need to rescale the images I use for nuclei prediction? Is there anything I should be aware of here?

Cheers
Pradeep

**Comment by pr4deepr** [comment]
I checked the shapes of the arrays (xyz):
`input_segmentation.shape `was: 577 x 453 x 378
whereas the `watershed.shape `was smaller:  284 x 223 x 79.. 

The larger shapes corresponds to the rescaled image. So, I rescaled the nuclei label image to match the shape of the rescaled membrane prediction. The shape mismatch error disappeared, but now I get another error:

```
Traceback (most recent call last):
  File "/home/rajasekhar.p/.conda/envs/plant-seg/bin/plantseg", line 10, in <module>
    sys.exit(main())
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/run_plantseg.py", line 28, in main
    raw2seg(config)
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/pipeline/raw2seg.py", line 85, in raw2seg
    output_paths = pipeline_step()
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/pipeline/steps.py", line 55, in __call__
    return [self.read_process_write(input_path) for input_path in self.input_paths]
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/pipeline/steps.py", line 55, in <listcomp>
    return [self.read_process_write(input_path) for input_path in self.input_paths]
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/segmentation/lmc.py", line 105, in read_process_write
    output_data = self.process(pmaps)
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/segmentation/lmc.py", line 73, in process
    segmentation = segment_volume_lmc_from_seg(boundary_pmaps,
  File "/home/rajasekhar.p/.conda/envs/plant-seg/lib/python3.8/site-packages/plantseg/segmentation/lmc.py", line 184, in segment_volume_lmc_from_seg
    lifted_costs = lifted_costs[:, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

I checked the shape of `lifted_costs ` and its (1070,), i.e., its a 1D array. 
So, I commented out this line  [lifted_costs = lifted_costs[:, 0]](https://github.com/hci-unihd/plant-seg/blob/b17a12f91b06c3c965347e1d96ab76c6ab750f62/plantseg/segmentation/lmc.py#L183)
The segmentation now works without a problem. 

Is there anything that I'm doing wrong or is it a bug with the program? Is it worth adding a check to see if its a 2D or 1D array?

Cheers
Pradeep

**Comment by pr4deepr** [comment]
Hi @lorenzocerrone 

  Thanks for the reply. 

For `elf`:

> python-elf | 0.4.0 | pyhd8ed1ab_0 | conda-forge

For `plantseg`

> plantseg | 1.4.2 |  py_1 | lcerrone

Also, are there any plans to bring it to Windows in the near future, apart from using docker?

Cheers
Pradeep

**Comment by lorenzocerrone** [comment]
We actually as of today have native support for windows. I am still testing it around, so I still expect bugs. In the readme you can find the installation instructions. 

Best,
Lorenzo

**Comment by pr4deepr** [comment]
Yes, please!! 
I'm happy to test and give feedback..

**Comment by lorenzocerrone** [comment]
Thanks! that would be awesome! :)

**Comment by pr4deepr** [comment]
It seems to be working fine on Windows. It was a breeze to install as everything is in one conda command. 
Will let you know if I run into any trouble..

**Comment by lorenzocerrone** [comment]
Perfect, thanks a lot for testing it.

In the next days (maybe a week) we will release stand alone binaries for Windows, and a new launcher to allow drag and drop of images and configs on Windows. If you are mostly on Windows those could be useful for you.

Cheers, 
Lorenzo

**Comment by pr4deepr** [comment]
Hi
 I'm having trouble with segmentations using the lifted multicut in PlantSeg. Due to data confidentiality, I'm not allowed to share the data publicly. Is it ok if I send the data link in an email?

Cheers
Pradeep

**Comment by qin-yu** [comment]
Hey @pr4deepr, I think this problem was fixed in the Napar interface a long time ago (but after this issue ofc). Do you still experience any issue relating to Lifted MultiCut? If not I'll close the issue. Thanks for reporting!

**Comment by pr4deepr** [comment]
Hi
  I haven't used this in a while, but I remember it working for me. 
I'll close this and reopen if needed.

Cheers
Pradeep
